### PR TITLE
Set the end date when adding to calendar

### LINKED ISSUE #305: Event reminder has a wrong end date
In the agenda html5 app, you can add the event to your calendar (after you marked yourself as GOING). Then an ICS file is email to your account. However this ics file doesnt contain the event end date. Also there is nothing shown after you pressed the button. Show a message that the user will receive an email with an event invitation.

### PR DESCRIPTION
**Pull request by abom**
Closes #305.
When adding an event to calendar, end date was not sent, also show a message after adding to calendar that an email will be sent.

### CODE REVIEW

File: src/solutions/common/templates/brandings/app_events.js [hunk 1]
```diff
@@ -278,27 +283,38 @@
         $("#detail").data("option_type", option_type);
 
         var now = (new Date().getTime()) / 1000;
-        var upcommingEvents = getUpcommingStartAndEndDates(event, now, false);
+        var upcommingEvents = getUpcommingStartAndEndDates(event, now, true);
 
         $.each(upcommingEvents, function (ui, upcomming_event) {
-            var eventDate = new Date(upcomming_event.start.year, upcomming_event.start.month - 1, upcomming_event.start.day, upcomming_event.start.hour, upcomming_event.start.minute);
+            var eventDate = toDateObject(upcomming_event.start);
```
Comment (RubenMattan) [inline src/solutions/common/templates/brandings/app_events.js]: i think you forgot ```.getTime() / 1000;```

File: src/solutions/common/bizz/events.py [hunk 2]
```diff
@@ -499,10 +499,13 @@ def solution_add_to_calender_event(service_user, email, method, params, tag, ser
     event.add('description', jsondata['eventDescription'])
     event.add('location', jsondata['eventPlace'])
     startDate = datetime.utcfromtimestamp(int(jsondata['eventStart']))
+    endDate = datetime.utcfromtimestamp(int(jsondata['eventEnd']))
```
Comment (RubenMattan) [inline src/solutions/common/bizz/events.py]: please try catch this, because old brandings will send an object instead of an epoch

File: src/solutions/common/templates/brandings/app_events.js (hunk 1 above)
Comment (abom) [inline src/solutions/common/templates/brandings/app_events.js]: After conversion to date object?
eventStart and eventEnd are converted the next lines (getTime() / 1000).

Comment (RubenMattan) [inline src/solutions/common/templates/brandings/app_events.js]: my bad ;-)

Comment (abom) [inline src/solutions/common/templates/brandings/app_events.js]: No problem at all :laughing:
